apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-financeiro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-financeiro
  template:
    metadata:
      labels:
        app: api-financeiro
    spec:
      containers:
      - name: api-financeiro
        image: joleques/api_financeiro:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
